project:
  type: book
  output-dir: docs

book:
  title: "Enterprise Information Architecture"
  author: "Xing Song"
  date: "8/20/2025"
  chapters:
    - index.qmd
    - intro_arch.qmd
    - intro_it.qmd
    - hist_hit.qmd
    - hmis.qmd
    - glossary.qmd
    - pbl1_id.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

