project:
  type: book
  output-dir: docs

book:
  title: "Enterprise Information Architecture"
  author: "Xing Song"
  date: "8/20/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

