project:
  type: book
  output-dir: docs

book:
  title: "Enterprise Information Architecture"
  author: "Xing Song"
  date: "8/20/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - pbl1_ls.qmd
    - pbl2_ds.qmd
    - pbl3_hb.qmd
    - pbl4_dq.qmd
    - pbl5_ai.qmd
    - pbl6_open.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

