project:
  type: book
  output-dir: docs

book:
  title: "Enterprise Information Architecture"
  author: "Xing Song"
  date: "8/20/2025"
  chapters:
    - part: "Syllabus"
      chapters: 
        - index.qmd
    - part: "Chapters"
      chapters: 
        - intro_arch.qmd
        - intro_it.qmd
        - hist_hit.qmd
        - hmis.qmd
        - hit_hie.qmd
    - part: "PBL Assignments"
      chapters: 
        - pbl1_id.qmd
        - pbl2_cd.qmd
    - part: "Supplemental"
      chapters: 
        - glossary.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

